service: flow-4-rating

plugins:
  - serverless-python-requirements
  - serverless-offline-python
  - serverless-dynamodb-autoscaling

custom:
  serverless-offline:
    port: 3001
  pythonRequirements:
    dockerizePip: true

package:
  individually: true
  exclude:
    - ../../node_modules/**
    - ../../a/** # virtualenv
    - ../../venv/** # virtualenv

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:100987174432:table/*'
  versionFunctions: false

functions:
  handler:
    handler: handler.handler
    provisionedConcurrency: 100
    timeout: 900 # API Gateway limits it to 30s
    memorySize: 3008 # max value
    events:
      - stream: arn:aws:dynamodb:us-east-1:100987174432:table/tmp_results_step2/stream/2020-11-27T18:43:56.733
