service: flow-2-search

plugins:
  - serverless-python-requirements
  - serverless-offline-python

custom:
  serverless-offline:
    port: 3001
  pythonRequirements:
    dockerizePip: true

package:
  individually: true
  exclude:
    - ../../node_modules/**
    - ../../a/** # virtualenv
    - ../../venv/** # virtualenv

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: 'arn:aws:dynamodb:us-east-1:100987174432:table/tmp_results_step1'
  versionFunctions: false

functions:
  handler:
    handler: handler.handler
    timeout: 900
    memorySize: 3008 # max value
    provisionedConcurrency: 100
    events:
      - stream: arn:aws:dynamodb:us-east-1:100987174432:table/tmp_searches/stream/2020-11-27T22:16:16.325


